"""empty message

Revision ID: 7577801f4577
Revises: e17301df8558
Create Date: 2023-06-27 11:42:20.712320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7577801f4577'
down_revision = 'e17301df8558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('board_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'card', 'board', ['board_id'], ['board_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'board_id')
    # ### end Alembic commands ###
