"""Remove likes count and make board id required

Revision ID: b620d0fba919
Revises: 7577801f4577
Create Date: 2023-06-28 10:43:16.332980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b620d0fba919'
down_revision = '7577801f4577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('card', 'likes_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('likes_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('card', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
